# Generated by Django 5.0 on 2024-05-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryPopulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(blank=True, max_length=10, null=True)),
                ('female_population', models.CharField(blank=True, max_length=10, null=True)),
                ('male_population', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Country Population',
            },
        ),
    ]
